## Домашнее задание «Библиотека numpy. Вычислительные задачи»
### Задание 1
Создайте numpy array с элементами от числа N до 0\
например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [44]:
import numpy as np
N = int(input('Введите N: '))
rvr=np.arange(0, N)[::-1]
print (rvr)

Введите N: 14
[13 12 11 10  9  8  7  6  5  4  3  2  1  0]


### Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [45]:
diag_mat = np.diag(rvr)
print(diag_mat)

print('cумма на диагонали= ',  np.trace(diag_mat))

[[13  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 12  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 11  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 10  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  9  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  8  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  7  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  6  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  5  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  4  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  3  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  2  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]]
cумма на диагонали=  91


### Задание 3
Решите систему уравнений:
$$4x + 2y + z = 4$$
$$x + 3y = 12$$
$$5y + 4z = -3$$

In [42]:
from numpy import linalg
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
b = np.array(  [4, 12, -3] )
sol=np.linalg.solve(a, b)
check=np.allclose( np.dot(a, linalg.solve(a, b)), b )
print (sol, check)

[ 0.46666667  3.84444444 -5.55555556] True


### Задача 4
Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [18]:
import numpy as np
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)
pd.DataFrame(table, columns=["User ID","Смартфон", "Smart TV", "Ноутбук", "Шкаф", "Холодильник", "Посуда"])

User ID  Смартфон  Smart TV  Ноутбук  Шкаф  Холодильник  Посуда
0        1         2         1        0     0            0       0
1        2         1         1        2     1            0       0
2        3         2         0        1     0            0       0
3        4         1         1        2     1            0       1
4        5         0         0        1     2            0       0
5        6         0         0        0     0            0       5
6        7         1         0        0     0            0       0
7        8         0         1        1     0            0       0
8        9         0         0        0     1            1       3
9       10         1         0        0     2            1       4

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [19]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [25]:
def cosine(users_stats, next_user_stats):
    max_Length = 0
    aLength = np.linalg.norm( next_user_stats )
    for i in range(len(users_stats)):
        bLength = np.linalg.norm( users_stats[i] )
        array_length = np.dot( next_user_stats, users_stats[i] ) / ( aLength * bLength )
        if max_Length <= array_length:
            max_Length = array_length
            id_number = i
    print('User_ID самого похожего пользователя:', id_number, '( сходство: =', max_Length,')')
cosine(users_stats, next_user_stats)

User_ID самого похожего пользователя: 7 ( сходство: = 0.9486832980505138 )
